name: NodeJS CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
          
jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Build docker
        run: docker-compose build
        
      - name: Docker up
        run: docker-compose up -d
